#! /bin/bash

# run the script like this:
# $ chmod +x ./path/to/top
# $ ./path/to/top 10 ./path/to/log.txt

# here comes your solution
# e.g.


awk '{print $4}' log.txt | tr -d [- | cut -c1-11 | sort | uniq -c | sort -nrk4| head -n5 | sed -e 's/,/\n/g' | cat -n 
